import type { Config } from 'tailwindcss';

export const safelist = [
  'absolute',
  'animate-spin',
  'bg-white',
  'block',
  'border-2',
  {
    pattern: /border-(gray|rose|amber)-300/,
  },
  'border-slate-200',
  'border',
  'bottom-0',
  'cursor-pointer',
  'flex',
  {
    pattern: /border-(gray|rose|amber)-500/,
    variants: ['focus'],
  },
  'focus:outline-none',
  'font-sans',
  'font-semibold',
  'group',
  {
    pattern: /text-(gray|rose|amber)-500/,
    variants: ['group-focus-within'],
  },
  'h-5',
  'invisible',
  'items-center',
  'justify-center',
  'left-0',
  'left-3',
  'opacity-25',
  'opacity-75',
  'pointer-events-none',
  'pt-2',
  'px-1',
  'px-4',
  'px-6',
  'py-2',
  'relative',
  'right-0',
  'rounded-md',
  'select-none',
  {
    pattern: /text-(gray|rose|amber)-400/,
  },
  {
    pattern: /text-(gray|rose|amber)-900/,
  },
  'text-amber-500',
  'text-gray-500',
  'text-rose-500',
  'text-slate-800',
  'text-xs',
  'top-0',
  'w-5',
  'w-full',
] as Config['safelist'];
